#!/usr/bin/env python3
"""
Dive AI - Automated API Key Setup
Generates .env file with API keys for secure configuration
"""

import os
import sys
from pathlib import Path

# Default API keys (can be overridden)
DEFAULT_KEYS = {
    "V98API_KEY": os.getenv("V98API_KEY", "YOUR_V98_API_KEY_HERE"),
    "AICODING_API_KEY": os.getenv("AICODING_API_KEY", "YOUR_AICODING_API_KEY_HERECJCk"),
}

def print_banner():
    """Print setup banner"""
    print("=" * 70)
    print("🔐 DIVE AI - API KEY SETUP")
    print("=" * 70)
    print()

def check_existing_env():
    """Check if .env file already exists"""
    env_path = Path(".env")
    if env_path.exists():
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if response != 'y':
            print("❌ Setup cancelled. Existing .env file preserved.")
            sys.exit(0)
        print()

def get_api_keys():
    """Get API keys from user or use defaults"""
    print("📝 API Key Configuration")
    print("-" * 70)
    print()
    print("Press ENTER to use default keys, or enter your own:")
    print()
    
    keys = {}
    
    # V98API Key
    print(f"1. V98API Key")
    print(f"   Default: {DEFAULT_KEYS['V98API_KEY'][:20]}...")
    v98_key = input("   Enter key (or press ENTER for default): ").strip()
    keys['V98API_KEY'] = v98_key if v98_key else DEFAULT_KEYS['V98API_KEY']
    print()
    
    # AICoding Key
    print(f"2. AICoding API Key")
    print(f"   Default: {DEFAULT_KEYS['AICODING_API_KEY'][:20]}...")
    aicoding_key = input("   Enter key (or press ENTER for default): ").strip()
    keys['AICODING_API_KEY'] = aicoding_key if aicoding_key else DEFAULT_KEYS['AICODING_API_KEY']
    print()
    
    # Optional keys
    print("3. OpenAI API Key (Optional)")
    openai_key = input("   Enter key (or press ENTER to skip): ").strip()
    if openai_key:
        keys['OPENAI_API_KEY'] = openai_key
    print()
    
    print("4. Anthropic API Key (Optional)")
    anthropic_key = input("   Enter key (or press ENTER to skip): ").strip()
    if anthropic_key:
        keys['ANTHROPIC_API_KEY'] = anthropic_key
    print()
    
    return keys

def create_env_file(keys):
    """Create .env file with API keys"""
    env_content = """# Dive AI - API Configuration
# Generated by setup_api_keys.py
# DO NOT COMMIT THIS FILE TO GIT!

# V98Store API Configuration
V98API_KEY={v98api_key}

# AICoding API Configuration
AICODING_API_KEY={aicoding_key}

# OpenAI API Configuration (Optional)
{openai_line}

# Anthropic API Configuration (Optional)
{anthropic_line}

# Additional Configuration
DIVE_AI_ENV=production
DIVE_AI_LOG_LEVEL=INFO
""".format(
        v98api_key=keys['V98API_KEY'],
        aicoding_key=keys['AICODING_API_KEY'],
        openai_line=f"OPENAI_API_KEY={keys.get('OPENAI_API_KEY', '')}" if 'OPENAI_API_KEY' in keys else "# OPENAI_API_KEY=your_key_here",
        anthropic_line=f"ANTHROPIC_API_KEY={keys.get('ANTHROPIC_API_KEY', '')}" if 'ANTHROPIC_API_KEY' in keys else "# ANTHROPIC_API_KEY=your_key_here"
    )
    
    # Write .env file
    with open('.env', 'w') as f:
        f.write(env_content)
    
    # Set file permissions (read/write for owner only)
    os.chmod('.env', 0o600)
    
    print("✅ .env file created successfully!")
    print(f"   Location: {Path('.env').absolute()}")
    print(f"   Permissions: 600 (owner read/write only)")
    print()

def create_env_example():
    """Create .env.example template"""
    example_content = """# Dive AI - API Configuration Template
# Copy this file to .env and fill in your API keys
# DO NOT COMMIT .env TO GIT!

# V98Store API Configuration
V98API_KEY=your_v98api_key_here

# AICoding API Configuration
AICODING_API_KEY=your_aicoding_key_here

# OpenAI API Configuration (Optional)
# OPENAI_API_KEY=your_openai_key_here

# Anthropic API Configuration (Optional)
# ANTHROPIC_API_KEY=your_anthropic_key_here

# Additional Configuration
DIVE_AI_ENV=production
DIVE_AI_LOG_LEVEL=INFO
"""
    
    with open('.env.example', 'w') as f:
        f.write(example_content)
    
    print("✅ .env.example template created!")
    print()

def verify_setup():
    """Verify the setup"""
    print("🔍 Verifying setup...")
    print()
    
    # Check .env exists
    if not Path('.env').exists():
        print("❌ ERROR: .env file not found!")
        return False
    
    # Try to load environment variables
    try:
        from dotenv import load_dotenv
        load_dotenv()
        
        v98_key = os.getenv('V98API_KEY')
        aicoding_key = os.getenv('AICODING_API_KEY')
        
        if not v98_key:
            print("⚠️  WARNING: V98API_KEY not found in .env")
        else:
            print(f"✅ V98API_KEY loaded: {v98_key[:20]}...")
        
        if not aicoding_key:
            print("⚠️  WARNING: AICODING_API_KEY not found in .env")
        else:
            print(f"✅ AICODING_API_KEY loaded: {aicoding_key[:20]}...")
        
        print()
        return True
        
    except ImportError:
        print("⚠️  python-dotenv not installed. Installing...")
        os.system("pip install python-dotenv")
        print("✅ python-dotenv installed!")
        print()
        return True

def print_next_steps():
    """Print next steps"""
    print("=" * 70)
    print("✅ SETUP COMPLETE!")
    print("=" * 70)
    print()
    print("📋 Next Steps:")
    print()
    print("1. Your API keys are now stored in .env (secured)")
    print("2. The .env file is automatically ignored by git")
    print("3. Run your Dive AI installation:")
    print()
    print("   python3 install_pipeline.py")
    print()
    print("4. Or start using Dive AI directly:")
    print()
    print("   python3 dive_ai_startup.py")
    print()
    print("⚠️  IMPORTANT:")
    print("   - Never commit .env to git")
    print("   - Keep your API keys secret")
    print("   - Share .env.example (not .env) with others")
    print()
    print("=" * 70)

def main():
    """Main setup function"""
    print_banner()
    
    # Check existing .env
    check_existing_env()
    
    # Get API keys
    keys = get_api_keys()
    
    # Create .env file
    create_env_file(keys)
    
    # Create .env.example
    create_env_example()
    
    # Verify setup
    verify_setup()
    
    # Print next steps
    print_next_steps()

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ ERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
