"""Project Scaffold Skill — Generate project boilerplate."""
import os, json
from ..base_skill import BaseSkill
from ...algorithms.base import AlgorithmResult
from ..skill_spec import SkillSpec, SkillCategory

TEMPLATES = {
    "python": {"files": ["main.py", "requirements.txt", "README.md", ".gitignore", "tests/__init__.py"],
               "main.py": '"""Generated by Dive AI."""\n\ndef main():\n    print("Hello from {name}!")\n\nif __name__ == "__main__":\n    main()\n',
               "requirements.txt": "# Add dependencies here\n", ".gitignore": "__pycache__/\n*.pyc\n.env\nvenv/\n"},
    "node": {"files": ["index.js", "package.json", "README.md", ".gitignore"],
             "index.js": "// Generated by Dive AI\nconsole.log('Hello from {name}!');\n",
             "package.json": '{{"name": "{name}", "version": "1.0.0", "main": "index.js"}}',
             ".gitignore": "node_modules/\n.env\n"},
    "web": {"files": ["index.html", "style.css", "script.js", "README.md"],
            "index.html": '<!DOCTYPE html>\n<html><head><title>{name}</title><link rel="stylesheet" href="style.css"></head>\n<body><h1>{name}</h1><script src="script.js"></script></body></html>\n',
            "style.css": "body {{ font-family: Inter, sans-serif; }}\n", "script.js": "// Generated by Dive AI\n"},
    "api": {"files": ["app.py", "requirements.txt", "README.md", ".env.example"],
            "app.py": 'from flask import Flask, jsonify\napp = Flask(__name__)\n\n@app.route("/api/health")\ndef health():\n    return jsonify({{"status": "ok", "name": "{name}"}})\n\nif __name__ == "__main__":\n    app.run(debug=True)\n',
            "requirements.txt": "flask\n", ".env.example": "PORT=5000\n"},
}

class ProjectScaffoldSkill(BaseSkill):
    def _build_spec(self):
        return SkillSpec(name="project-scaffold", description="Generate project boilerplate: Python, Node, Web, API",
            category=SkillCategory.CODING, version="1.0.0",
            input_schema={"name": {"type": "string", "required": True}, "template": {"type": "string", "required": True},
                          "path": {"type": "string"}},
            output_schema={"created_files": "list", "path": "string"},
            tags=["scaffold", "project", "boilerplate", "create", "init", "new"],
            trigger_patterns=[r"(new|create)\s+project", r"scaffold", r"init\s+", r"boilerplate"],
            combo_compatible=["git-ops", "code-review", "file-manager"],
            combo_position="start")

    def _execute(self, inputs, context=None):
        name = inputs.get("name", "my-project")
        template = inputs.get("template", "python")
        base = inputs.get("path", os.path.expanduser(f"~/projects/{name}"))
        
        tmpl = TEMPLATES.get(template)
        if not tmpl:
            return AlgorithmResult("failure", None, {"error": f"Unknown template: {template}. Available: {list(TEMPLATES.keys())}"})
        
        created = []
        for fname in tmpl["files"]:
            fpath = os.path.join(base, fname)
            os.makedirs(os.path.dirname(fpath), exist_ok=True)
            content = tmpl.get(fname, f"# {name}\n\nGenerated by Dive AI\n").format(name=name)
            with open(fpath, "w", encoding="utf-8") as f:
                f.write(content)
            created.append(fname)
        
        return AlgorithmResult("success", {"created_files": created, "path": base, "template": template, "name": name},
                               {"skill": "project-scaffold"})
